library/urls.py
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.book_list, name='book_list'),
    path('books/<int:id>', views.book_detail, name='book_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('search/', views.search_book, name='search_book'),
    path('delete_book/<int:id>', views.delete_book, name='delete_book'),
]

mini_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='library')),
]

library/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Managers
class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Book.Status.PUBLISHED)

# Create your models here.
class Book(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DR", 'Draft'
        PUBLISHED = "PB", 'Published'
        REJECTED = "RJ", 'Rejected'

    # relations
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_books')
    # data fields
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=205)
    price = models.IntegerField(default=0)
    description = models.TextField()
    genre = models.CharField(max_length=250)
    number_of_pages = models.IntegerField(default=0)
    slug = models.SlugField(max_length=250)
    # date fields
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # choice fields
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    publish = PublishManager()

    class Meta:
        ordering = ['-published']
        indexes = [
            models.Index(fields=['-published']),
        ]
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

library/forms.py
from django import forms

from library.models import Book


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'author',
            'price',
            'description',
            'genre',
            'number_of_pages',
        ]

class SearchForm(forms.Form):
    query = forms.CharField()

library/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.template.defaultfilters import title

from .models import Book
from .forms import *

# Create your views here.
def index(request):
    return render(request, 'library/index.html')

def book_list(request):
    books = Book.publish.all()
    context = {
        'books': books,
    }
    return render(request, 'library/list.html', context)

def book_detail(request, id):
    try:
        book = Book.publish.get(id=id)
    except:
        raise Http404('Book not found')
    context = {
        'book': book,
    }
    return render(request, 'library/detail.html', context)

def add_book(request):
    if request.method == "POST":
        form = AddBookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user
            book.save()
            return redirect('library:index')
    else:
        form = AddBookForm()
    return render(request, 'forms/add_book.html', {'form': form})

def search_book(request):
    query=None
    results = []
    if "query" in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Book.publish.filter(title__icontains=query)
            results2 = Book.publish.filter(author__icontains=query)
            results = results1 | results2
    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'library/search.html', context)

def delete_book(request, pk):
    book = get_object_or_404(Book, id=pk)
    if request.method == "POST":
        book.delete()
        return redirect('library:index')
    return render(request, 'forms/delete_book.html', {'book': book})

library/templates/forms/add_book.html
{% extends 'parent/base.html' %}
{% block title %}add book{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
{% endblock %}

library/templates/forms/delete_book.html
{% extends 'parent/base.html' %}
{% block title %}delete book{% endblock %}
{% block content %}
    <a href="{% url 'library:index' %}"> return to main menu</a>
    <br>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="delete">
    </form>
{% endblock %}

library/templates/library/detail.html
{% extends 'parent/base.html' %}
{% block title %}book detail{% endblock %}
{% block content %}
    <h1>Book detail</h1>
    <h2>{{ book.title }} (by {{ book.author }})</h2>
    <p>{{ book.description | linebreaks }}</p>
    <hr>
    <p>{{ book.published }}</p>
{% endblock %}

library/templates/library/index.html
{% extends 'parent/base.html' %}
{% block title %}Library Management{% endblock %}
{% block content %}
    <h1>Library Management</h1>
    <h2>
        <a href="{% url 'library:book_list' %}">Books list</a>
    </h2>
    <h2>
        <a href="{% url 'library:add_book' %}">Add new book</a>
    </h2>
{#    <h2>#}
{#        <a href="{% url 'forms:delete_book' %}">Delete book</a>#}
{#    </h2>#}
{% endblock %}

library/templates/library/list.html
{% extends 'parent/base.html' %}
{% block title %}books list{% endblock %}
{% block content %}
    <h1>Books list</h1>
    {% for book in books %}
        <h2>
        <a href="{% url 'library:book_detail' book.id %}">{{ book }}</a>
        </h2>
        <p>{{ book.description|truncatewords:3 }}</p>
    {% endfor %}
{% endblock %}

library/templates/library/search.html
{% extends 'parent/base.html' %}
{% block title %}searched books{% endblock %}
{% block content %}
   {% if query %}
       Search results for "{{ query }}". {{ results.count }} books found.
   {% endif %}
    <br>
    {% for book in results %}
        <a href="{{ book.get_absolute_url }}">{{ book.title }} </a>
        {% empty %}
            Nothing found!
    {% endfor %}
{% endblock %}

library/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body dir="ltr">
{% include 'partials/header.html' %}
{% include 'partials/navigation.html' %}
{% block content %}{% endblock %}
{% include 'partials/footer.html' %}

</body>
</html>

library/templates/partials/header.html
<form method="get" action="{% url 'library:search_book' %}">
    {% csrf_token %}
    <input type="text" name="query" required placeholder="enter your name or author's book...">
    <input type="submit" value="search">
</form>